// Derived collision rows: one bit per 16-pixel NES quadrant cell.
const encodedRounds = [
  "A8ADwAMAAwAD4APgA+gD6ADgAOAA4ADgAOAA4ADAAOAAAACAAOgA6APgA+AD4APgA+AD4APgA+AzgAPAADwAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAwADAAMAAwADwAPAA8IDwAPAA8ADwAPAA8ADwAPAA8ADwAPAF8AXwAfAB8AHwAfABwAHAAcABwADAAcAAAABAPAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAwAAAAAAAAMAAwADAAMAAwADAAMAAwADAAMAAAAAAADAAMAAwADAAMAAwADAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAOAA6ADoAOAA4ADgAOAA4ADgAMAA4AAAAIAAAAAAAAA8AAAAAAAAAgAAAAAAAAAAAAAAAAAAAOAA4APgA+AD4APgA+AD4APgA+ADgAPAAAAAAADAAMAAwADAA8ADwAPAA8ADwAPAA8ADwADAAMADwAPA",
  "B/wf4AD+AP4A/gD+AP4A/gD+AP4A/gD+APAA/AIAAMAGAAMAAwAGAAAAAgAEAAAABAAEAAEgBQABgAEgAAAAgAD+APwA/gD+AP4A/gD+AP4A/AD+AAAA4AYAAAACoASgAIACgD8ADwD/AH8AfwD/AAcAHwAAIAAgAIAAgAAgACAAAAAAAAAAAAABAAFAAQABQABAAAAAQAAAgACAKAAgAAAACAAEAAQABQAFAAEAAQAAAAAAAAAAAAD/APzA/4D/gP/A/wDgAP4AAAAAAAAAAAcABwA/AAcAfwB/AH8AfwB/AH8ADwA/AAAAAwAAAAAAAIAAAABAAMACAABgAIACgAACAACAAAACAAKAAAEAAAIBAAEABAAFAASgBCAAAACAAAAAAAD4APAP+A/4P/g/+Af4H/gA+AD4APAA+AAAAMAAAAAAAAAAAAAAAAAGAAAAA4AGgAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoACAAAAAIA8ADwA/4D/A",
  "AAAAAAAAAAAAAAAAAAAAAAYABgACAAIAYAAAACAAYAAMACwABAAEAAAAAAAAAAAAAAAAAAAAAAAAwAAAAPAA4ADgAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAPAA4ADgAPAAAAAAAAAAAAAAAAAAAAAABgAGAAIAAgBgAAAAIABgAAwALAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAPAAcABwAPAAAAAAAAZgBgAEQARgAwAAQAIAAwAAwAIAAIAAwAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAYAYgBiACAAIACAAQAAgACAAQAAgAAYAAAACAAYAIABiAGAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYABgACYAJgACAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYABgACAAIAAAAAABgAGAAIAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAADwAOAA4ADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAIARABgAAYARAAAAAQAAAAAADAAMAAgACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAA8ADgAOAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
  "AAAAAAAAAAAA8ADAAPAA8ADgAPAA/AD4AMwA3AA/AHwA/wD/AP4A/8D/gP/A/8D/AP4A/wD4APwA4ADwAIAAwAAAAAAA8ADAAPAA8ADgAPAA/AD4AMwA3AA/AHwA/wD/APwA/gD4APwA4ADwAIAAwAAAAAAA8ADAAPAA8ADgAOAA/AD4APgA/AD/APgA/wD/AP4A/sD/gP+A/8D/AP4A/wD4APwA4ADwAIAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAMADwAPAA8ABwA/AB8APwA/AP8APwD/AP8A/wD/AP8D/wH/A/8DfwD/AB8APwAHAA8AAQADAAAAAAAPAAMADwAPAA8ABwA/AB8APwA/AP8APwD/AP8APwB/AA8AHwADAAcAAAABAAAAAAAPAAMADwAPAAcABwA/AB8APwA/AP8AHwD/AP8AfwB/AP8D/wH/A/8DfwD/AB8APwAHAA8AAQADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8ADAAPAA8ADgAOAA/AD4APgA/ADgAPAAgADAAAAAAAAAAAAA8ADAAPAA8ADgAPAA/AD4APwA/ADgAPAAgADA",
  "wP/A/4DnwG+A/4D/AOyA3wDvAO8ANgA/AAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAOAAwADgAPYANgDeAPYAHgAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAEAHgAfAA8AGwDtAe8B3wD/AW8AfgA/AG8APwA8AA8ADwAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAcAGwAfAA8AGAD/AP8A/wH2AP8BnwFnAG8ABwAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAADwAPAAfgB+wP/AfsD/wPPA/MBs",
  "APAA8AD/AP8A/wD/AP8A/wD/AP8A/gD/AAAAAAAAAAAA4ADQADAAUADAAMAAAAAA/wD/AP8A/wB/AP8AAPAA8EDwAPAA8IDwAPAA8ADwAPAB8ADwA/AD8AvgB/AEAAEAAgABAAAAAAAAwABAAMAA0ADgANAA0ABAAEAAAAAAAAAAAAAAAAAAAAAAAAA/8D/wP/A/8D/wP/Af/D/8APwA/AD8APwA+AD8APAA8AHgAPADAAsADgAFABMAAwADAAcACAAEAAAAAAAAAAAAQAAAACAAEAAAgABAAOAA0AAAAEAAgABQANsAxwDgANADAAMAA0ADEA8ADwAP8A/wD/AP8P/w//D/8P/w/+D/8H8A/wAAwADQAHAAGAAEAAAAAAAAAwABAAD/Av8A/wD/AP8A/wD+AP8AAAAAIAAQAAAAAAAAAAAAAAAAAADAAMAHIgdSB/IH0gdABwAHIAcQBwAHCAPwB/Af8B/wH/Af8B/wH/Af8B/wf/B/8H/wf/B/4H/wPwB/AB8wHxAfAB8ADwAfAAAAAAAAAAAAAAAAAAAAAAAAAwAFgABAAAADAAvADEAGAANAAwAAAAAAAAAAAAAAAAD8APwA/AD8APwA/DD4EPwAAAAAAAAAAAAAAAB/wH9Af4B/QH/Qf8B/AH9AfwB/gH8AfwA/AH8AAPAA8ADwAPAA8ADwAP8A/wD/AP8A/wD/AP4A/wwABAAAAAAAAAAAIADAAMAA0ABAAAAAQAAAAAAAAAAAAAAAABMAAwAPAScAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAEABPAC8APwAfAM8AzwAPAA8A==",
] as const;

const decodeRows = (encoded: string): readonly number[] => {
  const bytes = atob(encoded);
  const rows = new Array<number>(bytes.length / 2);
  for (let index = 0; index < rows.length; index += 1) {
    rows[index] = bytes.charCodeAt(index * 2) | (bytes.charCodeAt(index * 2 + 1) << 8);
  }
  return rows;
};

export const ROUND_COLLISION_ROWS: readonly (readonly number[])[] = encodedRounds.map(decodeRows);
export const ROUND_COLLISION_ROW_COUNTS = ROUND_COLLISION_ROWS.map((rows) => rows.length);

const NES_MAP_WIDTH = 256;
const NES_MAP_ROW_PIXELS = 32;
const NES_VIEW_HEIGHT = 240;
const WORLD_WIDTH = 960;
const WORLD_HEIGHT = 540;
const INITIAL_STORAGE_ROW = 8;

export function roundCollisionBlocks(round: number, scroll: number, x: number, y: number): boolean {
  const rows = ROUND_COLLISION_ROWS[round - 1];
  if (!rows) return false;
  const mapRows = rows.length / 2;
  const scrollNes = Math.max(0, Math.floor(scroll * NES_VIEW_HEIGHT / WORLD_HEIGHT));
  const fineScroll = (16 + scrollNes) & 31;
  const page = fineScroll < 16 ? 1 : 0;
  const pointerStorageRow = (INITIAL_STORAGE_ROW + Math.floor(scrollNes / NES_MAP_ROW_PIXELS)) % mapRows;
  const screenX = Math.max(0, Math.min(NES_MAP_WIDTH - 1, Math.round(x * NES_MAP_WIDTH / WORLD_WIDTH + 8)));
  const screenY = Math.max(0, Math.min(255, Math.round((y - scroll) * NES_VIEW_HEIGHT / WORLD_HEIGHT + 6)));
  const relativeY = (screenY - fineScroll + 256) & 255;
  const byteOffset = ((relativeY & 0xe0) >> 2) + 8 + (page ? 8 : 0);
  const storageRow = (pointerStorageRow - byteOffset / 8 + mapRows) % mapRows;
  const traversalRow = (storageRow - INITIAL_STORAGE_ROW + mapRows) % mapRows;
  const row = traversalRow * 2 + Number(Boolean(relativeY & 0x10));
  const bit = 15 - ((screenX >> 5) * 2 + Number(Boolean(screenX & 0x10)));
  return Boolean((rows[row] ?? 0) & (1 << bit));
}
